-- 005_note_sharing.sql
-- Add writing_mode persistence to notes_pages
ALTER TABLE notes_pages
  ADD COLUMN IF NOT EXISTS writing_mode VARCHAR(20) DEFAULT NULL;

-- Note share tokens — generated by owner, consumed by recipient
CREATE TABLE IF NOT EXISTS note_shares (
  id          VARCHAR(36)  PRIMARY KEY,
  token       VARCHAR(64)  NOT NULL UNIQUE,
  page_id     VARCHAR(36)  NOT NULL,
  shared_by   INT UNSIGNED NOT NULL,
  expires_at  DATETIME     NOT NULL,
  created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (page_id)   REFERENCES notes_pages(id) ON DELETE CASCADE,
  FOREIGN KEY (shared_by) REFERENCES users(id) ON DELETE CASCADE
);
